server:
  port: 20101

spring:
  application:
    name: demoa
  cloud:
    nacos:
      discovery:
        # 指定nacos server地址
        server-addr: 192.168.52.128:8848
    stream:
      binders:
        mztuRabbitBinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.52.128
                port: 35672
                username: ttx
                password: ttx2011
                virtualHost: /cloud-dev
      bindings:
        dpb-exchange-input1:
          destination: miniExchange
          binders: mztuRabbitBinder
#          content-type: application/json
#          consumer:
#            partitioned: true
#          group: miniExchange-group1
        dpb-exchange-input2:
          destination: miniExchange
          binders: mztuRabbitBinder
        dpb-exchange-output:
          destination: miniExchange
          binders: mztuRabbitBinder

      rabbit:
        bindings:
          dpb-exchange-output:
            producer:
              routingKeyExpression: '''afterTestEvent'''
          dpb-exchange-input1:
            consumer:
              bindingRoutingKey: afterTestEvent
          dpb-exchange-input2:
            consumer:
              bindingRoutingKey: afterTestEvent
